Implemented getopts. Cleaned up old sed replaced by foamDictionary.

diff --git a/Allrun b/Allrun
--- a/Allrun
+++ b/Allrun
@@ -9,10 +9,27 @@ regions="cavity"
 
 neutronTransport="neutronTransport"
 
-rootCase="rootCase"
-# rootCase="rootCase_samofar"
+# Reference cases for mapping
+fluidRef="0.1"
+neutroRef="0.2"
+energyRef="0.3" # not used at the moment, but could be used to accelerate case 1.3
 
-cases="0.1 0.2 0.3 1.1 1.3 1.5" #"0.1 0.2 0.3 1.1 1.3 1.5"
+# Settings
+run=true
+
+rootCase="rootCase"
+
+cases="0.1 0.2 0.3 1.1 1.3 1.5 1.7"
+power="0.0 0.2 0.4 0.6 0.8 1.0"
+velocity="0.0 0.1 0.2 0.3 0.4 0.5"
+
+runMaybe()
+{
+    if [ "$run" = true ] ; then
+        ( cd $caseName && runApplication `getApplication` )
+    fi
+
+}
 
 runMapFields()
 {
@@ -95,12 +112,6 @@ setNeutronicsCase() # case 0.2
     foamDictionary $caseName/system/$regions/fvSolution -entry "PIMPLE.initializeSubSolver" -set "true"
     foamDictionary $caseName/system/controlDict -entry "endTime" -set "150"
     foamDictionary $caseName/system/controlDict -entry "deltaT" -set "1.0"
-    # controlDict="$caseName/system/controlDict"
-    # sed \
-    # -e s/"\(endTime[ \t]*\) 200;"/"\1 150;"/g \
-    # -e s/"\(deltaT[ \t]*\) 0.01;"/"\1 1.0;"/g \
-    # $controlDict > temp.$$
-    # mv temp.$$ $controlDict
 
     printf "Case set!\n\n"
 }
@@ -111,17 +122,9 @@ setEnergyCase() # case 0.3
     foamDictionary $caseName/system/$regions/fvSolution -entry "PIMPLE.frozenFlow" -set "true"
     foamDictionary $caseName/system/controlDict -entry "startTime" -set "200"
     foamDictionary $caseName/system/controlDict -entry "endTime" -set "270"
-    # controlDict="$caseName/system/controlDict"
-    # sed \
-    # -e s/"\(startTime[ \t]*\) 0;"/"\1 200;"/g \
-    # -e s/"\(endTime[ \t]*\) 200;"/"\1 270;"/g \
-    # $controlDict > temp.$$
-    # mv temp.$$ $controlDict
 
     runMapFields $caseName $fluidRef $regions
     cp $neutroRef/150/$regions/volPowerFuel* $caseName/200/$regions/
-    # runMapFields $caseName $neutroRef $regions/$neutronTransport
-    # runMapFields $caseName $fluidRef $thermalMechanics
     printf "Case set!\n\n"
 }
 
@@ -141,19 +144,9 @@ setCirculatingFuelCase()
     foamDictionary $caseName/system/controlDict -entry "startTime" -set "200"
     foamDictionary $caseName/system/controlDict -entry "endTime" -set "400"
     foamDictionary $caseName/system/controlDict -entry "deltaT" -set "1.0"
-    # controlDict="$caseName/system/controlDict"
-    # sed \
-    # -e s/"\(startTime[ \t]*\) 0;"/"\1 200;"/g \
-    # -e s/"\(endTime[ \t]*\) 200;"/"\1 270;"/g \
-    # -e s/"\(deltaT[ \t]*\) 0.01;"/"\1 1.0;"/g \
-    # -e s/"\(solveFluidMechanics[ \t]*\) true;"/"\1 false;"/g \
-    # -e s/"\(solveNeutronics[ \t]*\) false;"/"\1 true;"/g \
-    # $controlDict > temp.$$
-    # mv temp.$$ $controlDict
 
     runMapFields $caseName $fluidRef $regions
     runMapFields $caseName $neutroRef $regions/$neutronTransport
-    # runMapFields $caseName $fluidRef $thermalMechanics
     printf "Case set!\n\n"
 }
 
@@ -170,19 +163,9 @@ setPowerCouplingCase()
     foamDictionary $caseName/constant/$regions/solverProperties -entry "fluidDynamicsSolver" -set "porousGenFoamNuclear"
     foamDictionary $caseName/system/controlDict -entry "startTime" -set "200"
     foamDictionary $caseName/system/controlDict -entry "endTime" -set "270"
-    # controlDict="$caseName/system/controlDict"
-    # sed \
-    # -e s/"\(startTime[ \t]*\) 0;"/"\1 200;"/g \
-    # -e s/"\(endTime[ \t]*\) 200;"/"\1 270;"/g \
-    # -e s/"\(solveFluidMechanics[ \t]*\) true;"/"\1 false;"/g \
-    # -e s/"\(solveEnergy[ \t]*\) false;"/"\1 true;"/g \
-    # -e s/"\(solveNeutronics[ \t]*\) false;"/"\1 true;"/g \
-    # $controlDict > temp.$$
-    # mv temp.$$ $controlDict
 
     runMapFields $caseName $fluidRef $regions
     runMapFields $caseName $neutroRef $regions/$neutronTransport
-    # runMapFields $caseName $fluidRef $thermalMechanics
     printf "Case set!\n\n"
 }
 
@@ -196,14 +179,6 @@ setBuoyancyCase()
     foamDictionary $caseName/constant/$regions/solverProperties -entry "fluidDynamicsSolver" -set "porousGenFoamNuclear"
     foamDictionary $caseName/system/controlDict -entry "endTime" -set "80"
     foamDictionary $caseName/system/controlDict -entry "deltaT" -set "0.05"
-    # controlDict="$caseName/system/controlDict"
-    # sed \
-    # -e s/"\(endTime[ \t]*\) 200;"/"\1 80;"/g \
-    # -e s/"\(deltaT[ \t]*\) 0.01;"/"\1 0.05;"/g \
-    # -e s/"\(solveEnergy[ \t]*\) false;"/"\1 true;"/g \
-    # -e s/"\(solveNeutronics[ \t]*\) false;"/"\1 true;"/g \
-    # $controlDict > temp.$$
-    # mv temp.$$ $controlDict
 
     activateBuoyancy $caseName
     modifyTopWallVelocity $caseName 0 #stop top wall movement
@@ -217,12 +192,6 @@ setFullCoupling() # $1 = case velocity, $2 = case power
 {
     printf "Setting case $caseName with power $1 and top wall velocity $2...\n"
     foamDictionary $caseName/constant/$regions/solverProperties -entry "fluidDynamicsSolver" -set "porousGenFoamNuclear"
-    # controlDict="$caseName/system/controlDict"
-    # sed \
-    # -e s/"\(solveEnergy[ \t]*\) false;"/"\1 true;"/g \
-    # -e s/"\(solveNeutronics[ \t]*\) false;"/"\1 true;"/g \
-    # $controlDict > temp.$$
-    # mv temp.$$ $controlDict
 
     activateBuoyancy $caseName
     modifyTopWallVelocity $caseName $1
@@ -232,9 +201,73 @@ setFullCoupling() # $1 = case velocity, $2 = case power
 
 # PHASE 2 - transient capabilities testing
 
-fluidRef="0.1"
-neutroRef="0.2"
-energyRef="0.3" # not used at the moment, but could be used to accelerate case 1.3
+__usage="
+Usage: Allrun [OPTIONS]
+
+Options:
+    -C <string>     Customize the cases executed.
+                    e.g.: Allrun -C \"1.5 1.7\"
+                    defaults to $cases
+
+    -h              Show this help dialogue
+
+    -p              Something something something help
+
+    -P <string>     Customize power of cases 1.7.
+                    e.g.: Allrun -P \"0.0 1.0\"
+                    defaults to $power
+
+    -s              Execute SAMOFAR cases instead of normal one
+
+    -V <string>     Customize velocity of cases 1.7.
+                    e.g.: Allrun -V \"0.0 0.2 1.0\"
+                    defaults to $velocity
+"
+
+while getopts ":C:hpP:sV:" opt;do
+    case $opt in
+    # a)
+    #     printf "Executing ALL cases! This will take a long time... go do something else for 2 DAYS!\n\n"
+    #     # Also check if the case is not already run (exists and has last timestep). If it does, skip and issue warning on &2.
+    #     ;;
+    C)
+        cases=$OPTARG
+        printf "Cases set to $cases\n\n"
+        ;;
+    h)
+        echo "$__usage"
+        exit 0
+        ;;
+    p)
+        printf "Preparing cases only! Will not run.\n\n"
+        run=false
+        ;;
+    P)
+        power=$OPTARG
+        printf "Power for case 1.7 set to $power\n\n"
+        ;;
+    # r)
+    #     printf "Running existing cases\n\n"
+    #     # check if the case was not run already (exists and has last timestep). If it does, skip and issue warning on &2.
+    #     ;;
+    s)
+        printf "Executing with SAMOFAR root\n\n"
+        rootCase="rootCase_samofar"
+        ;;
+    # t)
+    #     printf "Test single physics coupled stages full coupling\n\n"
+    #     # fairly complex function that takes $OPTARG string and does stuff
+    #     ;;
+    V)
+        velocity=$OPTARG
+        printf "Velocity for case 1.7 set to $velocity\n\n"
+        ;;
+    \?)
+        printf "Invalid option: -$OPTARG\nExecute Allrun -h for help on using the script.\n" >&2
+        exit 1
+        ;;
+    esac
+done
 
 for caseName in $cases
 do
@@ -249,86 +282,65 @@ do
     case "$caseName" in
     "0.1")
         printf "Case 0.1 is prepared!\n"
+        runMaybe
         ;;
     "0.2")
         printf "Case 0.2 entered...\n"
         setNeutronicsCase
+        runMaybe
         ;;
     "0.3")
         printf "Case 0.3 entered...\n"
         setEnergyCase
+        runMaybe
         ;;
     "1.1")
         printf "Case 1.1 entered...\n"
         setCirculatingFuelCase
+        runMaybe
         ;;
     "1.3")
         printf "Case 1.3 entered...\n"
         setPowerCouplingCase
+        runMaybe
         ;;
     "1.5")
         printf "Case 1.5 entered...\n"
         setBuoyancyCase
+        runMaybe
+        ;;
+    "1.7")
+        printf "Cases 1.7 entered...\n"
+
+        for powerI in $power
+        do
+            for velocityI in $velocity
+            do
+                caseName="1.7_P${powerI}_U${velocityI}"
+
+                printf "Preparing to run case $caseName...\n"
+
+                printf "Cloning rootCase to case $caseName..."
+                cloneCase rootCase $caseName
+                printf "rootCase cloned!\n"
+
+                runBlockMesh $caseName
+
+                if [ $powerI = "0.0" ]; then
+                    power0="0.0000001"
+                    setFullCoupling $velocityI $power0
+                else
+                    setFullCoupling $velocityI "${powerI}e+09"
+                fi
+
+                runMaybe
+            done
+        done
         ;;
     esac
 
-    ( cd $caseName && runApplication `getApplication` )
-done
-
-power="" #"0.0 0.2 0.4 0.6 0.8 1.0"
-velocity="" #"0.0 0.1 0.2 0.3 0.4 0.5"
-
-for powerI in $power
-do
-    for velocityI in $velocity
-    do
-        caseName="1.7_P${powerI}_U${velocityI}"
-
-        printf "Preparing to run case $caseName...\n"
-
-        printf "Cloning $rootCase to case $caseName..."
-        # cloneCase ../$rootCase $caseName
-        cloneCase $rootCase $caseName
-        printf "$rootCase cloned!\n"
-
-        runBlockMesh $caseName
-
-        if [ $powerI = "0.0" ]; then
-            power0="0.0000001"
-            setFullCoupling $velocityI $power0
-        else
-            setFullCoupling $velocityI "${powerI}e+09"
-        fi
-
-        ( cd $caseName && runApplication `getApplication` )
-    done
 done
 
 
-# while getopts ":ahp:rt:" opt;do
-#     case $opt in
-#     a)
-#         printf "Executing ALL cases! This will take a long time... go do something else for 2 DAYS!\n\n"
-#         # Also check if the case is not already run (exists and has last timestep). If it does, skip and issue warning on &2.
-#         ;;
-#     h)
-#         printf "Help!\n\n"
-#         ;;
-#     p)
-#         printf "Preparing cases\n\n"
-#         ;;
-#     r)
-#         printf "Running existing cases\n\n"
-#         # check if the case was not run already (exists and has last timestep). If it does, skip and issue warning on &2.
-#         ;;
-#     t)
-#         printf "Test single physics coupled stages full coupling\n\n"
-#         # fairly complex function that takes $OPTARG string and does stuff
-#         ;;
-#     \?)
-#         printf "Invalid option: -$OPTARG\nExecute Allrun -h for help on using the script.\n" >&2
-#         ;;
-#     esac
-# done
 
 #------------------------------------------------------------------------------
